### PR TITLE
Updated Icebrood Saga Strike Missions

### PR DESCRIPTION
**Pull request by Linkaaaaa**
## Icebrood Construct
- Separated Ice Arm Swing into Hit and CC mechanic
- Added Frostbite, Spinning Ice, Deadly Shockwave enemy cast, Ice Arm Swing enemy cast
- Renamed some mechanics
## Kodans
- Added Groundshaker, Groundpiercer, Unrelenting Pain buff, Deadly Synergy enemy cast, Teleport cast
## Fraenir of Jormag
- Renamed some mechanics
- Added Ice Arm Swing, Frigid Fusillade, Frozen Missile (hit and cast), Seismic Crush (hit and cast), 
- Renamed the phases to make them more clear
- Added Bound Icebrood Elemental as npcs to EvtcParse and a way to check wether they have been destroyed or they have spawned the Icebrood Elemental npc
- Added icons for Bound and normal Icebrood Elementals
## Boneskinner
- Removed stability check from Death Wind, the attack always strips it before knocking down the players
- Added Grasp, Cascade, Barrage, Crushing Cruelty, Unrelenting Pain buff, Breakbar and Exposed
- Added torches as npcs to EvtcParse
- Added icons for torches and wisps
## Whisper of Jormag
- Fixed Chains application buff icon
- Changed teleport in and out buffs icon
- Added Slithering Rime, Frigid Vortex (buff, damage and cast), Launch up in air, Ice Shatter, Lethal Coalescence cast
## Overall
- Fixed some code formatting
- Removed some unnecessary ParserHelper. and SkillIDs. references
- Added a GetPoint3D helper method to AbstractMovementEvent
- Added Point3D constructor that accepts a tuple

### CODE REVIEW

**Comment by EliphasNUIT** [comment]
Could you restore the short name attributes you have changed please? They are used as identifier by 3rd parties so they shouldn't be modified without a very important reason.

Thanks.

**Comment by Linkaaaaa** [comment]
Sure, wanted to streamline the naming scheme as Skill.H for hits, .A for buff application and .CC for cc, but i guess that isn't possible then?

**Comment by EliphasNUIT** [comment]
Those are not supposed to be streamlined, you can however modify Full Name and Descriptions as you see fit.

**Comment by Linkaaaaa** [comment]
They should be all reverted now

**Comment by EliphasNUIT** [comment]
Thanks!

**Pull request merged**
