### PR TITLE
Boons: fractal potions and mistlock singularity

### PR DESCRIPTION
**Pull request by cordbleibaum**

### CODE REVIEW

**Comment by EliphasNUIT** [comment]
The potions should be consumables, not standard buffs.

**Comment by cordbleibaum** [comment]
ok, switched pots consumable, there is still the issue tho that there are apparently no stackable consumables yet

**Comment by EliphasNUIT** [comment]
It'll be properly displayed on the graph. Shouldn't be difficult to adapt GetConsumables() on Player.cs to take that into account

**Comment by cordbleibaum** [comment]
the problem is in the player tab every consumable stack gets displayed as a seperate consumable making it hard to read

**Comment by LunusLupus** [comment]
image

I don't see any issue here.

**Comment by EliphasNUIT** [comment]
if everything is applied at the same time, we can easily do consumable (stacks) when applicable, if someone takes during a fight potions 1 by 1, it'll appear that number of time in refreshed

**Comment by EliphasNUIT** [comment]
I'll merge this this evening, and add the stacking support to that part

**Pull request merged**
