### PR TITLE
Phases

### PR DESCRIPTION
**Pull request by EliphasNUIT**
- Added subphases to Dhuum's main phase separated by greater deathmarks + cata cycles
- Added phases to mursaat base on hp
- Added phases to slothasor based on breakbar
- Added phases to soulless horror based on breakbar

### CODE REVIEW

**Comment by Sejsel** [comment]
I am not sure the MO phases provide any useful data, I don't think it's necessary to have some kind of phases on each encounter.

Slothasor phases seem very useful, SH will have a variable amount of phases, but that shouldn't be an issue or confusing in any way.

The Dhuum phases are overlapping, right? At least that is what I am guessing by names. That might be a bit misleading if somebody thinks of phases as non-overlapping which was the case in EI for a long time.

**Comment by EliphasNUIT** [comment]
EI had overlapping phases since the very first day phases were implemented, with KC (burst phases included inside their respective main phases) and Deimos add phases have existed for at least half a year now which are basically sub phases of the 100% - 10% phase focused on Sauls. Largos also has overlapping phases by nature.  You could also argue that all the phases overlap with the full fight phase :P
For MO I've just put it because it was possible, some may found some use to it or not, does not cost to have it. That'll also be helpful if some day we animate the arena with the spear pattern.

**Comment by Sejsel** [comment]
Oh, yeah, I remember somebody being confused about KC phases, in that case it's not very well communicated. You are right about Deimos, forgot about that one. I guess Sabetha works similarly. If it's communicated well, like naming the phase pre-something as in this case, it's fine.

And it's true that the phases would be useful for the spear pattern, so I guess it's fine.

**Comment by EliphasNUIT** [comment]
Yeah I had changed some naming after the KC confusion and added pre-burn phases and leftover phases to it

**Pull request merged**
