### PR TITLE
Artsariiv & Arkk improvements

### PR DESCRIPTION
**Pull request by Zerthox**
Improvements for Arkk & Artsariiv encounters.

## Arkk
- Add "Bloom" (orb) phases (from first aware to last aware)
- Add missing trash mobs
- Add Corporal Reassignment (skull) dome & explosion decorations
- Add Cosmic Meteor (green) decoration
- Add Horizon Strike (pizza) decorations

## Artsariiv
- Add Corporal Reassignment (skull) dome & explosion decorations
- Add Beaming smile (laser) decorations
- Add Obliterate & "post-Obliterate" decorations

### CODE REVIEW

**Comment by Zerthox** [comment]
Should probably note here that Anet added a new skill id for the animation after Obliterate. The decorations for circles after Obliterate currently rely on that id.

**Comment by EliphasNUIT** [comment]
Any chance this could be merged soon?

**Comment by Zerthox** [comment]
Yes, I don't think I will add more decorations for now. Thoughts on the Arkk bloom phases ending on bloom last aware vs Arkk Invulnerability loss? Also I still wanted to check whether older logs have a CombatExit event for Anomaly "deaths" (there is no death even most of the time).

**Comment by EliphasNUIT** [comment]
For the bloom phases, the phase should end at min(max(bloomLastAwares), arkkInvulLoss ?? fightEnd), to make sure we don't have a situation when bloom last awares are a little bit delayed.
In terms of code, "PhaseData phase = phases.FirstOrDefault(x => Math.Abs(x.Start - start) < ServerDelayConstant);", are we sure that has 0% of chance of colliding with an existing phase?

**Comment by Zerthox** [comment]
I adjusted the bloom phases. Assuming no other changes are needed, how quickly do you want to merge this? Linka had the idea of adding instant cast detection for the special action key, which I could add to this PR or do in a separate one later.

**Comment by EliphasNUIT** [comment]
As soon as humanly possible, I have massive Decoration API rework going on in cleanup, I'd like to merge your additions into it and make the necessary migrations ASAP so that I can merge it into master.

**Comment by Linkaaaaa** [comment]
The sak can be added any other time, not necessary to do it now

**Comment by EliphasNUIT** [comment]
Thanks!

**Pull request merged**
