### PR TITLE
Fix thief venom stacks capacity

### PR DESCRIPTION
**Pull request by Linkaaaaa**
They got increased in the 25/06 patch
https://wiki.guildwars2.com/wiki/Game_updates/2024-06-25#Thief
[venoms.zip](https://github.com/user-attachments/files/16043896/venoms.zip)

### CODE REVIEW

**Comment by EliphasNUIT** [comment]
If there is something wrong with BuffInfoEvent.MaxStack it is better to report it to ArcDPS than try to do a by-pass.

**Comment by Linkaaaaa** [comment]
There's nothing wrong, the new buff capacity is logged correctly

**Comment by EliphasNUIT** [comment]
Then everything is working as expected no?

**Comment by Linkaaaaa** [comment]
Yes they work but do we want to keep the incorrect number there instead of splitting it with a game build?

**Comment by EliphasNUIT** [comment]
That is what we have been doing since the introduction of BuffInfoEvent half a decade ago, the burden of maintenance of capacity was shifted to it.

**Comment by Linkaaaaa** [comment]
Well nevermind then

**Pull request closed without merging**
